### ISSUE TITLE
A2A get password certificate file not found

### ISSUE THREAD

**Issue by daby0922** [OneIdentity/safeguard-bash#44]
Hi, I ran the a2a event handling on CentOS 7 and the cert uploaded to the certs folder inside a2a-event-handling. But it seems the cert is unable to found on the mount volume. 

[root@safeguard-api a2a-event-handling]# ./run.sh -v $(pwd)/certs --env-file <(cat <<EOF
SG_APPLIANCE=192.168.34.7
SG_CERTFILE=SGcert.pem
SG_KEYFILE=SGkey.pem
SG_APIKEY=USvyBHT7VIhv1Lizas5FwRogjC1zVFNkvisf6rWBtdI=
SG_KEYFILE_PASSWORD=password
EOF
)
Rebuilding the image: safeguard-certdemo ...
Using default tag: latest
Trying to pull repository docker.io/oneidentity/safeguard-bash ...
latest: Pulling from docker.io/oneidentity/safeguard-bash
Digest: sha256:2625b0fd1eab578e5493786db108fa9d01960e23d39e45ef6565a6108c8e4cd6
Status: Image is up to date for docker.io/oneidentity/safeguard-bash:latest
Sending build context to Docker daemon 49.66 kB
Step 1/5 : FROM oneidentity/safeguard-bash:latest
 ---> 912c457202df
Step 2/5 : MAINTAINER support@oneidentity.com
 ---> Running in 576166e60efe
 ---> fdb8a8e6515d
Removing intermediate container 576166e60efe
Step 3/5 : COPY sample-a2a-listener.sh /scripts/
 ---> 26c4fd0339a3
Removing intermediate container f1d5845a6a37
Step 4/5 : ENTRYPOINT /bin/bash
 ---> Running in 7b41cfa74875
 ---> 47362e3a5c21
Removing intermediate container 7b41cfa74875
Step 5/5 : CMD /scripts/sample-a2a-listener.sh
 ---> Running in 01bb6105c072
 ---> 7a493fa98c9e
Removing intermediate container 01bb6105c072
Successfully built 7a493fa98c9e
Checking for environment information
SGcert.pem certificate file not found in /volume/

**Comment by petrsnd** [comment]
Hi @daby0922 .  I'll take a look to see if I can help with a sample.  It doesn't look like you mounted the directory containing the certificate into the volume.

**Comment by petrsnd** [comment]
It looks like you are passing the argument correctly, of course, I can't see what is in your `$(pwd)/certs` directory.

```Terminal
$ ./run.sh -h
USAGE: run.sh [-v volume] [-h] [-c command]

  -h  Show help and exit
  -v  Directory from host to mount into container at /volume
      This is useful for mounting a directory with certificates and private keys
  -c  Alternate command to run in the container (often -c bash to get a prompt)
      Always specify the -c option last
```

Let me see if I can reproduce.

**Comment by petrsnd** [comment]
So, that sample requires that you run `./setup.sh` first which will create a `certs/` directory with certificates and private keys.  It will also create the A2A registration and set everything up inside your Safeguard instance.  Then, you have to call the `./run.sh` script exactly as written.

**Comment by petrsnd** [comment]
Actually the `certs/` directory is just checked in.

@daby0922 I tried to improve the instructions in the sample with #45 .

Please respond to this thread if you need any additional help.

**Comment by daby0922** [comment]
The sample path of cert folder should contains corresponding certificate and private key. I have ran the setup.sh before start run.sh. Do I missing something to successful run the script?

My environment: CentOS 7.6 with minimal install, install jq, docker and git, to clone the source to my local file. 

[root@safeguard-api ~]# cd /root/safeguard-bash/samples/event-handling/a2a-event-handling/
[root@safeguard-api a2a-event-handling]# ls  $(pwd)/certs
A2ATestCA.ca-bundle  A2ATestCA.cert.pem  A2AUser.cert.pem  A2AUser.key.pem  A2AUser.p12  issuing-A2ATestCA.cert.pem  SG.crt  SG-Encrypt.key

I tested to use the connection script to test, it seems normal. 

[root@safeguard-api a2a-event-handling]# connect-safeguard.sh -a 192.168.34.70 -i certificate -c $(pwd)/certs/SGcert.pem -k $(pwd)/certs/SGkey.pem
Password:
A login file has been created.

**Comment by petrsnd** [comment]
Maybe I'm missing what you are trying to do, but this sample is just a demo.  It uses demo data and insecure certificates that are checked into GitHub to show how A2A event listening works.

If you want to set up your own A2A registration and certificate user, then you will need to follow the documentation for your own files `SGcert.pem` and `SGkey.pem`.  Or, you can try to read the code in `setup.sh` and write your own script that does something similar.

In your output above you have:
```
# ./run.sh -v $(pwd)/certs --env-file <(cat <<EOF
SG_APPLIANCE=192.168.34.7
SG_CERTFILE=SGcert.pem
SG_KEYFILE=SGkey.pem
SG_APIKEY=USvyBHT7VIhv1Lizas5FwRogjC1zVFNkvisf6rWBtdI=
SG_KEYFILE_PASSWORD=password
EOF
)
```
You reference `SGcert.pem` and `SGkey.pem`.  The `setup.sh` script doesn't install those.  It is written to install the trusted certificates and the thumbprint from the user certificate included in the `certs/` directory.  I suppose if you wanted to rename your certificates to match what was already in the `certs/` directory, then maybe you could get this to work, but I think you would be better served just setting it up from scratch.

**Comment by daby0922** [comment]
That's Ok. I will rename my key and cert to match existing name later. However, I can get the password via get-a2a-password.sh command. Thanks,.

[root@safeguard-api a2a-event-handling]# echo 'password' | get-a2a-password.sh -r -a 192.168.34.70 -c $(pwd)/certs/SGcert.pem -k $(pwd)/certs/SGkey.pem -A 'McSG6FFgoI9udUh9hSKoPR7NNOXo/Uy0NvP86lMnatA='
